# Generated by Django 5.2.6 on 2025-09-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
        migrations.AddField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cor',
            field=models.CharField(blank=True, choices=[('Branca', 'Branca'), ('Preta', 'Preta'), ('Parda', 'Parda'), ('Amarela', 'Amarela'), ('Indígena', 'Indígena'), ('Outra', 'Outra')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('Infantil', 'Educação Infantil'), ('Fundamental I', 'Fundamental I (1º-5º)'), ('Fundamental II', 'Fundamental II (6º-9º)'), ('Médio', 'Ensino Médio'), ('Técnico', 'Técnico'), ('Superior', 'Superior'), ('EJA', 'EJA'), ('Outro', 'Outro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='rua',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
