# Generated by Django 5.2.6 on 2025-09-20 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_remove_aluno_data_nascimento_remove_aluno_email_and_more'),
        ('responsaveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='escolaridade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='VinculoAlunoResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Pai', 'Pai'), ('Mãe', 'Mãe'), ('Responsável Legal', 'Responsável Legal'), ('Outro', 'Outro')], default='Responsável Legal', max_length=20)),
                ('principal', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsaveis.responsavel')),
            ],
            options={
                'verbose_name': 'Vínculo aluno-responsável',
                'verbose_name_plural': 'Vínculos aluno-responsável',
                'unique_together': {('aluno', 'responsavel')},
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, related_name='alunos', through='alunos.VinculoAlunoResponsavel', to='responsaveis.responsavel'),
        ),
    ]
