# Generated by Django 5.2.6 on 2025-09-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('idade', models.PositiveIntegerField(blank=True, null=True)),
                ('rua', models.CharField(blank=True, max_length=200, null=True)),
                ('bairro', models.CharField(blank=True, max_length=120, null=True)),
                ('cidade', models.CharField(blank=True, max_length=120, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('cor', models.CharField(blank=True, choices=[('Branca', 'Branca'), ('Preta', 'Preta'), ('Parda', 'Parda'), ('Amarela', 'Amarela'), ('Indígena', 'Indígena'), ('Outra', 'Outra')], max_length=20, null=True)),
                ('escolaridade', models.CharField(blank=True, choices=[('Infantil', 'Educação Infantil'), ('Fundamental I', 'Fundamental I (1º-5º)'), ('Fundamental II', 'Fundamental II (6º-9º)'), ('Médio', 'Ensino Médio'), ('Técnico', 'Técnico'), ('Superior', 'Superior'), ('EJA', 'EJA'), ('Outro', 'Outro')], max_length=20, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
